site_name: Speaker Calibration Documentation
nav:
  - Home: index.md
  - Speaker Calibration:
    - Installation: installation.md
    - Usage: usage.md
    - Protocols: protocols.md
  - Latency Measurements:
    - Protocol: latency.md
theme:
  name: readthedocs