[tool.poetry]
name = "speaker-calibration"
version = "0.1.0"
description = ""
authors = [
    "Jos√© Grilo <jose.grilo@research.fchampalimaud.org>",
    "Naz Belkaya <naz.belkaya@research.fchampalimaud.org>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scipy = "^1.13.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 180