[tool.poetry]
name = "speaker-calibration"
version = "0.1.0"
description = ""
authors = [
    "Jos√© Grilo <jose.grilo@research.fchampalimaud.org>",
    "Naz Belkaya <naz.belkaya@research.fchampalimaud.org>"
]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scipy = "^1.13.1"
pyharp = {git = "https://github.com/harp-tech/pyharp", rev = "5856da12a78169921ad31bb184eb1a419519e3a0"}
pyyaml = "^6.0.1"
matplotlib = "^3.9.0"
moku = "^3.2.0"
nidaqmx = "^0.9.0"
setuptools = "^70.0.0"
urllib3 = "^2.2.1"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 180