# yaml-language-server: $schema=schemas/config-schema.json
soundcard: 
  serial_port: COM4
  fs: 192000
  speaker: Left
adc:
  fs: 250000
  device_id: 1
  channel: 1
filter:
  filter_input: true
  filter_acquisition: true
  min_freq: 5000
  max_freq: 20000
protocol:
  min_freq: 5000
  max_freq: 20000
  mic_factor: 0.41887
  reference_pressure: 0.00002
  eq_filter:
    sound_duration: 20
    time_constant: 0.005
    amplitude: 1
  calibration:
    sound_duration: 10
    min_amp: 0
    max_amp: -1
    amp_steps: 12
  test_calibration: 
    sound_duration: 5
    min_db: 30
    max_db: 68
    db_steps: 7
paths:
  output: output