# yaml-language-server: $schema=schemas/settings-schema.json
sound_type: Noise
reference_pressure: 0.00002
sound:
  ramp_time: 0.005
  amplification: 1
  freq:
    min_freq: 5000
    max_freq: 20000
  filter:
    filter_input: true
    filter_acquisition: true
    min_value: 5000
    max_value: 20000
  inverse_filter: 
    determine_filter: true
    sound_duration: 30
    time_constant: 0.005
  calibration:
    calibrate: true
    sound_duration: 15
    att_min: 0
    att_max: -1
    att_steps: 15
  test_calibration:
    test: true
    sound_duration: 5
    db_min: 30
    db_max: 70
    db_steps: 5