# yaml-language-server: $schema=schemas/settings-schema.json
sound_type: Noise
mic_factor: 0.41887
reference_pressure: 0.00002
ramp_time: 0.005
amplitude: 1
freq:
  min_freq: 5000
  max_freq: 20000
filter:
  filter_input: true
  filter_acquisition: true
  min_value: 5000
  max_value: 20000
inverse_filter: 
  determine_filter: true
  sound_duration: 1
  time_constant: 0.005
calibration:
  calibrate: true
  sound_duration: 1
  att_min: 0
  att_max: -1
  att_steps: 15
test_calibration:
  test: true
  sound_duration: 1
  db_min: 30
  db_max: 70
  db_steps: 5
is_harp: true
soundcard:
  com_port: COM17
  fs: 192000
is_nidaq: false
adc:
  fs: 500000
  address: fe80:0000:0000:0000:7269:79ff:feb9:62a2
output_dir: output