    fs_adc: 250000
    sound_duration_psd: 30
    sound_duration_db: 15
    sound_duration_test: 5
    ramp_time: 0.005
    reference_pressure: 0.00002
    mic_factor: 10
    att_min: 0
    att_max: -1
    att_steps: 15
    smooth_window: 1
    time_constant: 0.025
    freq_min: 5000
    freq_max: 20000
    freq_high: 4500
    freq_low: 25000
    amplification: 1
    sound_type: noise
