sound_type: Pure Tone
fs_adc: 250000
ramp_time: 0.005
amplification: 1
freq_min: 5000
freq_max: 20000
mic_factor: 10
reference_pressure: 0.00002
noise:
  calculate_filter: true
  calibrate: true
  test_calibration: true
  psd:
    duration: 30
    time_constant: 0.005
    smooth_window: 1
  calibration:
    duration: 15
    att_min: 0
    att_max: -1
    att_steps: 15
  test:
    duration: 5
    db_min: 30
    db_max: 70
    db_steps: 5
pure_tones:
  calibrate: true
  test_calibration: true
  calibration:
    duration: 0.15
    num_freqs: 5
    att_min: 0
    att_max: -1
    att_steps: 15
  test:
    duration: 0.15
    num_freqs: 5
    db_min: 30
    db_max: 70
    db_steps: 5